// src/config/admin-navigation.ts
// The navigation of the platform console. It is kept apart from the tenant
// navigation because the two answer different questions: one runs a business,
// the other runs the platform the businesses sit on.

import type { NavSection } from '@/config/navigation';

/** Sections shown to the platform team. */
export const ADMIN_NAV_SECTIONS: readonly NavSection[] = [
  {
    key: 'platform',
    label: 'Platform',
    items: [
      {
        key: 'admin-overview',
        label: 'Overview',
        href: '/admin',
        icon: 'dashboard',
        roles: ['super_admin'],
        isBuilt: true,
        isExact: true,
      },
      {
        key: 'admin-money',
        label: 'Money operations',
        href: '/admin/money',
        icon: 'payments',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-content',
        label: 'Website',
        href: '/admin/content',
        icon: 'marketplace',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-experiments',
        label: 'Tests',
        href: '/admin/experiments',
        icon: 'reports',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-measurement',
        label: 'Measurement',
        href: '/admin/measurement',
        icon: 'reports',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-platform',
        label: 'Platform operations',
        href: '/admin/platform',
        icon: 'settings',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-integrations',
        label: 'Connections',
        href: '/admin/integrations',
        icon: 'developers',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-settlements',
        label: 'Collection terms',
        href: '/admin/settlements',
        icon: 'payments',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-plans',
        label: 'Plans and codes',
        href: '/admin/plans',
        icon: 'subscriptions',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-verification',
        label: 'Verification',
        href: '/admin/verification',
        icon: 'admin',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-affiliates',
        label: 'Referral partners',
        href: '/admin/affiliates',
        icon: 'affiliate',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-partners',
        label: 'White label partners',
        href: '/admin/partners',
        icon: 'reseller',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-listings',
        label: 'Template marketplace',
        href: '/admin/listings',
        icon: 'marketplace',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-apps',
        label: 'Application review',
        href: '/admin/apps',
        icon: 'developers',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-storage',
        label: 'File storage',
        href: '/admin/storage',
        icon: 'files',
        roles: ['super_admin'],
        isBuilt: true,
      },
      {
        key: 'admin-tenants',
        label: 'Businesses',
        href: '/admin/tenants',
        icon: 'admin',
        roles: ['super_admin'],
        isBuilt: true,
      },
    ],
  },
];
